### ISSUE TITLE
command not found on mac

### ISSUE THREAD

**Issue by hwang1607** [UrielCh/npm-opencv-build#9]
I tried these and it says command not found: 

opencv-build-npm
npm-opencv-build 
build-opencv --nobuild rebuild

**Comment by hucorz** [comment]
same problem

**Comment by USS-Lexington** [comment]
try ` npx opencv-build-npm `

**Comment by UrielCh** [comment]
opencv-build-npm is present in the ./node_modules/.bin/ folder of the project.
- use npx opencv-build-npm
- or add ./node_modules/.bin in your PATH
- or call it as ./node_modules/.bin/opencv-build-npm
